# Generated by Django 4.1.3 on 2022-11-19 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('breakfast', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breakfast',
            name='slug',
        ),
    ]
